データベースを利用したメモアプリ
obregonia1/Public pull request #2
Opened 2021-02-17 01:33 UTC by obregonia1

確認よろしくお願いします。

2021-02-23 12:15 UTC, u1tnk requested changes

2021-02-23 12:15 UTC, u1tnk commented on memo.rb
> +create_str = 'CREATE TABLE if not exists memolist (title text not null unique, body text)'
起動時に作るようにしたんですね。
もちろん問題ありませんが、事前に作っとくだけでも大丈夫でした。参考まで。

2021-02-23 12:15 UTC, u1tnk commented on memo.rb
> +prepare_str = 'INSERT into memolist (title,body) values ($1,$2)'
update文のprepareが update_strならこちらは add_strでは無いでしょうか？

2021-02-23 12:15 UTC, u1tnk commented on memo.rb
> +update_str = 'UPDATE memolist set title=$1, body=$2 where title=$3'
titleで検索してる場合、同じタイトルが複数出るとおかしくなります。
タイトルとは別に数値のidを付けてidで管理すれば良いですね。

2021-02-23 12:15 UTC, u1tnk commented on memo.rb
> +  select_str = "SELECT body from memolist where title='#{title}'"
udpateでprepareを使ってますし、こちらもprepareを使うようにしましょう。
外部からもらった入力を文字列として使うのは SQLインジェクションという脆弱性を作る事になります。

2021-02-23 12:15 UTC, u1tnk commented on memo.rb
> +get '/memos/*/' do |title|
これでも良いのですが、

http://sinatrarb.com/intro-ja.html

の名前付きパラメータで 

`get /memos/:title/` do |title| `

とした方が見やすいと思います。

2021-02-23 12:15 UTC, u1tnk commented on memo.rb
> +  delete_str = "DELETE from memolist where title='#{title}'"
同上

2021-02-23 12:15 UTC, u1tnk commented on views/top.erb
> +  <% @titles.map do |title| %>
mapは配列を変換する目的のメソッドなので繰りかえすだけならeachを使いましょう。

2021-02-24 05:57 UTC, obregonia1 commented on memo.rb
> +prepare_str = 'INSERT into memolist (title,body) values ($1,$2)'
見落としていました💦
訂正しました。

2021-02-24 05:58 UTC, obregonia1 commented on memo.rb
> +update_str = 'UPDATE memolist set title=$1, body=$2 where title=$3'
titleをユニークにしていたんですが、idカラムを増やして同じタイトルが作れるように対応しました。

2021-02-24 05:59 UTC, obregonia1 commented on memo.rb
> +  select_str = "SELECT body from memolist where title='#{title}'"
了解しました！
仕様をidから取得するよう変更しました。

2021-02-24 05:59 UTC, obregonia1 commented on memo.rb
> +get '/memos/*/' do |title|
確かにわかりにくいですね🤔
変更しました。

2021-02-24 06:00 UTC, obregonia1 commented on views/top.erb
> +  <% @titles.map do |title| %>
了解しました！
訂正しました。

2021-02-24 23:15 UTC, merged